language: node_js

node_js:
  - v12

sudo: false

branches:
   only:
   - master

cache:
  directories:
    - ".eslintcache"
    - "node_modules"
    
install:
  - npm install
  
before_script:
script:
  - npm run build
